apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-app-secret
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: nishant-app-secret
  data:
    - secretKey: password
      remoteRef:
        key: MySecret
        property: password
